### ISSUE TITLE
Weired charactes in css files

### ISSUE THREAD

**Issue by magnusottosson** [skroonenburg/Rejuicer#2]
Hi,

When my css files are combined some weired character is added to the first line from each file. This makes the browser not recognize this line and the style is never added.

Take a look at: http://nixonnixon.apphb.com/nixonnixon-2421021430115041241691872925262219215129215.css

The css rule on line 2 and 4 are not recognized by the browser. If I past the content of a file in a texteditor (I use programmers notepad) I can see that some character has been added to these lines.

So I guess that there is some issue when the files are joined? it seems like this just happends for js files and not css files.

**Comment by magnusottosson** [comment]
I have nailed down the issue to PhysicalFileSource.cs.

Around line 90 you have:  var fileBytes = File.ReadAllBytes(PhysicalPath);
If I read out the string like:  var fileBytes = File.ReadAllBytes(PhysicalPath).ReadString() I get the error.
If I read out the string like: File.ReadAllLines(PhysicalPath, Encoding.UTF8); then there is no problem.

I will investigate more...

**Comment by magnusottosson** [comment]
Found the issue. When you join files the Byte Order Marks from the beginning of each file is not removed. I will submit a  patch.

**Comment by skroonenburg** [comment]
Thanks for reporting this issue, diagnosing and fixing!

I've merged the fix into the master branch and will update the binaries soon
